### ISSUE TITLE
Versions 0.9.0 and 0.9.1 don't appear in opam packages

### ISSUE THREAD

**Issue by tmcgilchrist** [anuragsoni/routes#143]
Neither 0.9.0 or 0.9.1 from https://github.com/anuragsoni/routes/releases appear in opam packages.
Were there issues with those 2 versions?

**Comment by anuragsoni** [comment]
Hi!

There are no issues with these two releases and they are functionally the same as the 1.0.0 published on opam. 

0.9.1 isn’t on opam as that just contained a package-metadata change needed for the npm package for use with buckle script. 0.9.0 isn’t on opam as I was initially waiting for some real world use to test out a few changes, and then ended up cutting a 1.0.0 release which is functionally identical to 0.9.1 and ended up publishing that to opam.

**Comment by tmcgilchrist** [comment]
Thanks for the answer, I'll just use 1.0.0

**Comment by anuragsoni** [comment]
Sounds good! I'd indeed recommending 1.0.0 if the requirement of needing dune >= 2.7 is acceptable.
