### ISSUE TITLE
Route.match' edge case question

### ISSUE THREAD

**Issue by john-kelly** [anuragsoni/routes#145]
first of all, great library! ive been doing a bit of [research](https://foldp.com/blog/elm-url.html) in this space and stumbled across your library. it's great! i've learned a lot from reading your code (this is my first time working with ocaml code! - other than reading some of oleg's stuff)

while experimenting, i ran into an edge case i was hoping to get information on.
```
utop # let helloworld () = Routes.(s "hello" / s "world" /? nil);;
val helloworld : unit -> ('a, 'a) target = <fun>
─( 16:32:04 )─< command 45 >─────────────────────────────────────{ counter: 0 }─
utop # let other () = Routes.(str / s "wow" /? nil);;
val other : unit -> (string -> 'a, 'a) target = <fun>
─( 16:35:00 )─< command 46 >─────────────────────────────────────{ counter: 0 }─
utop # let r1 () = Routes.(helloworld () @--> "Hello World");;
val r1 : unit -> string route = <fun>
─( 16:35:52 )─< command 47 >─────────────────────────────────────{ counter: 0 }─
utop # let r2 () = Routes.(other () @--> fun x -> x);;
val r2 : unit -> string route = <fun>
─( 16:36:54 )─< command 48 >─────────────────────────────────────{ counter: 0 }─
utop # let routes = Routes.one_of [r1 (); r2 ();];;
val routes : string router = <abstr>
─( 16:37:22 )─< command 49 >─────────────────────────────────────{ counter: 0 }─
utop # Routes.match' routes ~target:"/hello/world";;
- : string option = Some "Hello World"
─( 16:37:43 )─< command 50 >─────────────────────────────────────{ counter: 0 }─
utop # Routes.match' routes ~target:"/hello/wow";;
- : string option = None
```

should the last expression evaluate to `None` or `Some "hello"`?
```
utop # Routes.match' routes ~target:"/hello/wow";;
- : string option = None
```

is the current behavior expected? if not, i think the issue is here: https://github.com/anuragsoni/routes/blob/main/src/routes.ml#L52

specifically, you could return the result of dynamic `capture` in the case that static `children` parsing fails.

maybe you made this choice for perf reasons? 

looking forward to your response!

**Comment by anuragsoni** [comment]
Hello! Thank you for taking a look at this library!

> is the current behavior expected? if not, i think the issue is here:

The current behavior is indeed expect (I admit I haven't done the best job at documenting this :she

**Comment by anuragsoni** [comment]
Hello! Thank you for taking a look at this library!

> is the current behavior expected? if not, i think the issue is here:

The current behavior is indeed expect (I admit I haven't done the best job at documenting this 😅). When writing the route matching my thinking was that having the same node act as both an exact match, and a wildcard match (like in your example) would be a little confusing, and make it harder to predict how route matching is supposed to work. The current implementation seems easier to reason about for me personally. Performance wasn't the reason for making this choice, but reducing some backtracking helps I guess :)

**Comment by anuragsoni** [comment]
Excellent writeup about `elm/url`! While not quite the same, the first version of routes (https://github.com/anuragsoni/routes/blob/0.1.0/src/routes.ml) was closer in spirit to `elm/url`'s parser than where I've ended up today!

**Comment by anuragsoni** [comment]
> How would this be achieved? Would add return an option/result?

Since we can perform this check at the time we create a router instance, and when adding a new route to an existing router, we can have these functions return a result type that make it clear that this operation can result in errors. Adding an exception raising variant of these functions could also be nice in-case people would like to fail with an exception early on in the app lifecycle.

**Comment by john-kelly** [comment]
thanks so much for chatting about this!
