### ISSUE TITLE
Trailing slashes example in the README

### ISSUE THREAD

**Issue by mooreryan** [anuragsoni/routes#152]
Hey, I think this part of the readme (from line [165](https://github.com/anuragsoni/routes/blob/59bc7ec831e01199e07d9cf86d77304f829ef7b1/README.md?plain=1#L165) to 177) is left over from the pre 2.0 version.

The `//?` no longer exists and the code block given is the same as the one above but with a different function name. (Same functionality though.)

**Comment by anuragsoni** [comment]
Good catch! I'll update the readme. Thank you!
