### ISSUE TITLE
Extra param for trailing slash?

### ISSUE THREAD

**Issue by sazarkin** [anuragsoni/routes#50]
Maybe there is more elegant way to support `GET /health` and `GET /health/` for the same handler?

Right now I have to add 2 routes for this
```ocaml
[
  `GET, health <$ s "health";
  `GET, health <$ s "health" *> s ""
]
```

**Comment by anuragsoni** [comment]
Would an optional parameter used when configuring the router via `with_method` or `one_of` work for your needs?

Initially i was able to support this by providing a `choice` operation but that was removed a little while ago when i switched the backing store to a trie.

**Comment by sazarkin** [comment]
Yes, optional parameter is a good way

**Comment by anuragsoni** [comment]
Thanks for the quick response! I'll try and get to it this weekend. Also, if you would like to provide a patch i'm open to it as well.

**Comment by anuragsoni** [comment]
@sazarkin Hi, i started this at https://github.com/anuragsoni/routes/pull/52 Does this help your use case?

**Comment by sazarkin** [comment]
yes, looks perfect!

**Comment by anuragsoni** [comment]
Thanks! I'll add a few tests later today and then get this merged.

**Comment by anuragsoni** [comment]
This is available starting version 0.5.1 which was merged to the opam repository https://github.com/ocaml/opam-repository/pull/14521

**Comment by anuragsoni** [comment]
This was lost with the re-write on the master branch. This should be added back before the next release

**Comment by anuragsoni** [comment]
There's a slightly different version of this that's now present on the `master` branch
