### ISSUE TITLE
Forward additional custom data to handlers

### ISSUE THREAD

**Issue by Lupus** [anuragsoni/routes#59]
I really like the way Routes build function signatures on the fly! I was thinking about a way to extend this for passing for example parsed json body as additional named parameter to handler function. This way I can put all my decoders along with route specification and have handler be clean of dealing with invalid inputs and just consume properly typed structure for raw json input received. Is that currently possible?

**Comment by anuragsoni** [comment]
@Lupus Would you be able to describe your expected use as pseudo code? As long as the custom data neede by the handlers is of the same type i can see it working by having a wrapper around the match, like:

```ocaml
match Routes.match_with_method routes ~target:<target> ~meth:<method> with
| None -> <no match>
| Some handler -> handler (parsed request body, could be Yojson.json)
```

**Comment by Lupus** [comment]
Unfortunately each handler typically consumes unique json inputs. Something along these lines:

```ocaml
let decode_json decoder f ctx = f ~json_body:(decoder ctx) ctx                                                                                                                
                                                                                                                                                                              
let _ =                                                                                                                                                                       
  let open My_server in                                                                                                                                                       
  make ()                                                                                                                                                                     
  |> add `GET (Handlers.health <$ s "health")                                                                                                                                 
  |> add `GET (Handlers.list_items <$ s "v1" *> s "items")                                                                                                                    
  |> add `GET (Handlers.get_item <$> s "v1" *> s "items" *> str)                                                                                                              
  |> add `POST                                                                                                                                                                
       ( decode_json item_json_decoder                                                                                                                                        
       <$> (Handlers.create_item <$> s "v1" *> s "items" *> str) )
```

It does typecheck (maybe not this exact sample, but real code with same idea applied), but the route wrapped in decode_json does not get matched.

**Comment by Lupus** [comment]
Sorry, actually it does work! My bad, there was some extra int parameter at the end of the route DSL line which prevented it from matching. Extra parameter actually gets passed!

But `extra_processor <$> (handler <$> s "whatever")` requires manual parentheses to correct application order. Can this somehow be improved to move `extra_processor` at the end where it would seem more logical? Like `handler <$> s "whatever" *>> extra_processor`?

**Comment by Lupus** [comment]
I figured it out! With the below two operators I can add custom processing specific for each handler:

```ocaml
let (>*>) route processor_route = processor_route <*> route
let (>$>) route processor = processor <$> route

(* later in code *)
let decode_json decoder f ctx = f ~json_body:(decoder ctx) ctx
let dummy_decoder _ = "example string"
(* ... *)
Handlers.foo <$> s "foo" *> str >$> (decode_json dummy_decoder)
```

**Comment by anuragsoni** [comment]
That's an interesting approach!

Something else that i've done is like https://github.com/anuragsoni/routes/blob/09211e88e4cf320bdfe4a65690c3aba113576c0a/example/main.ml#L68-L71

Where I give every handler access to the Httpaf request descriptor (Reqd) So every handler has access to things that are relevant to a request lifecycle (this approach could also forward a context object that contains the request descriptor, access to other things like database connections, etc)

One reason that I kept the amount of public combinators small and simple was to keep it easy to translate to the backing untyped trie that is used for initial routing. 

I would indeed like to explore a routing layer that allows for custom actions like you mention. But maybe things like http method handling, query param handling could also be considered as a custom action, so i'd like to see if there can be a unified nice to use API for that, while still allowing for a reasonably performant easy to use default case of path based route dispatch.

**Comment by Lupus** [comment]
Well, Httpaf request descriptor is a must in a handler. We've had some success when trying to follow middleware model described in [opium](http://rgrinberg.com/posts/middleware-intro/). We stack some filters, which might not only pass normal request structure (including Reqd), but the one wrapped in higher business logic entities, which might include db connection etc. Not to mention the Core.Univ_map passed across all middlewares/filters allowing us to instrument the request with arbitrary extensions. Customizing route to specific json encoder/decoder is top notch in this type safe heaven :)

I believe this issue can be closed so as not to clutter the issue tracker. Thanks!

**Comment by anuragsoni** [comment]
I really like the filter approach inside opium (It was straightforward to plug the router as a opium middleware) If the app you are working on is open source i'd be very interested in learning about the approach you take :) 

Thanks for opening the issue!! I'm very interested in learning about how this library is actually being used as its good feedback for something that has helped me explore many different concepts about designing things with types :)

**Comment by Lupus** [comment]
May be we'll opensource it one day, so far it's in early development stage in-house. Approach is quite simple - arrange different stacks of filters with associated handlers into so called "handler sets", and then add handler sets into your server. Routing happens before any filter kicks in, which might not be desired behavior for everybody, but it's fine for our use case. Overall it's like having multiple Opium `App`'s in one http server, but with more type-safe router, thanks to `Routes`! :heart:

**Comment by anuragsoni** [comment]
Thank you! That sounds like an interesting approach to structuring the app via opium's filters!
