### ISSUE TITLE
Ability to get human readable name for route

### ISSUE THREAD

**Issue by sazarkin** [anuragsoni/routes#64]
It will be nice to get a pattern name, for example `/api/city/<int>/<int>`.

**Comment by anuragsoni** [comment]
This will indeed be very nice to have. I'd say this should also be used to support as a toplevel printer so when constructing routes in the REPL (utop) one would see the pattern printed out.

This could be done in a similar fashion to what we do to extract the patterns for the underlying untyped trie.

**Comment by anuragsoni** [comment]
This was lost with the re-write on the master branch. This should be added back before the next release
