### ISSUE TITLE
Expose an add method which allows a user to add a new route to the router trie

### ISSUE THREAD

**Issue by anuragsoni** [anuragsoni/routes#65]

**Comment by tatchi** [comment]
Hey,

If I understand it correctly, it should be something with a definition like:

```ocaml
val add : 'b route -> 'b router -> 'b router
```

Taking a route and an existing router as input, and returning a new router right?

**Comment by anuragsoni** [comment]
Hi @tatchi,

The function signature that you defined looks correct :)
